### DATA CLEANING

In [1]:
import pandas as pd
from sqlalchemy import create_engine
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Load the Dataset
df=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\INTERVIEW\DA Projects\DataCo Smart Suppy chain\DataCoSupplyChainDataset.csv",encoding="latin1")

In [2]:
df.shape

NameError: name 'df' is not defined

In [4]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 128.3 MB

In [6]:
df["order date (DateOrders)"] = pd.to_datetime(df["order date (DateOrders)"])
df["shipping date (DateOrders)"] = pd.to_datetime(df["shipping date (DateOrders)"])

In [7]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round(df.isnull().mean() * 100, 2)
})

missing[missing["Missing Values"] > 0].sort_values(
    by="Percentage",
    ascending=False
)

                     Missing Values  Percentage
Product Description          180519      100.00
Order Zipcode                155679       86.24
Customer Zipcode                  3        0.00
Customer Lname                    8        0.00

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["Order Id"].duplicated().sum()

np.int64(114767)

In [10]:
df.drop(columns=["Product Description", "Order Zipcode"], inplace=True)

In [12]:
df.duplicated().sum()
0

0

In [13]:
# Standardize Column Names
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("(", "", regex=False)
      .str.replace(")", "", regex=False)
      .str.replace("/", "_")
)

In [14]:
df.columns.tolist()

['type',
 'days_for_shipping_real',
 'days_for_shipment_scheduled',
 'benefit_per_order',
 'sales_per_customer',
 'delivery_status',
 'late_delivery_risk',
 'category_id',
 'category_name',
 'customer_city',
 'customer_country',
 'customer_email',
 'customer_fname',
 'customer_id',
 'customer_lname',
 'customer_password',
 'customer_segment',
 'customer_state',
 'customer_street',
 'customer_zipcode',
 'department_id',
 'department_name',
 'latitude',
 'longitude',
 'market',
 'order_city',
 'order_country',
 'order_customer_id',
 'order_date_dateorders',
 'order_id',
 'order_item_cardprod_id',
 'order_item_discount',
 'order_item_discount_rate',
 'order_item_id',
 'order_item_product_price',
 'order_item_profit_ratio',
 'order_item_quantity',
 'sales',
 'order_item_total',
 'order_profit_per_order',
 'order_region',
 'order_state',
 'order_status',
 'product_card_id',
 'product_category_id',
 'product_image',
 'product_name',
 'product_price',
 'product_status',
 'shipping_date_dateorders',
 'shipping_mode']

In [15]:
df["order_date_dateorders"] = pd.to_datetime(df["order_date_dateorders"])
df["shipping_date_dateorders"] = pd.to_datetime(df["shipping_date_dateorders"])

### FEATURE ENGINEERING

In [16]:
df["order_year"] = df["order_date_dateorders"].dt.year
df["order_month"] = df["order_date_dateorders"].dt.month
df["order_month_name"] = df["order_date_dateorders"].dt.month_name()
df["order_day"] = df["order_date_dateorders"].dt.day
df["order_weekday"] = df["order_date_dateorders"].dt.day_name()

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 56 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   type                         180519 non-null  str
 1   days_for_shipping_real       180519 non-null  int64
 2   days_for_shipment_scheduled  180519 non-null  int64
 3   benefit_per_order            180519 non-null  float64
 4   sales_per_customer           180519 non-null  float64
 5   delivery_status              180519 non-null  str
 6   late_delivery_risk           180519 non-null  int64
 7   category_id                  180519 non-null  int64
 8   category_name                180519 non-null  str
 9   customer_city                180519 non-null  str
 10  customer_country             180519 non-null  str
 11  customer_email               180519 non-null  str
 12  customer_fname               180519 non-null  str
 13  customer_id                  180519 non-null  int64
 14  customer_lname               180511 non-null  str
 15  customer_password            180519 non-null  str
 16  customer_segment             180519 non-null  str
 17  customer_state               180519 non-null  str
 18  customer_street              180519 non-null  str
 19  customer_zipcode             180516 non-null  float64
 20  department_id                180519 non-null  int64
 21  department_name              180519 non-null  str
 22  latitude                     180519 non-null  float64
 23  longitude                    180519 non-null  float64
 24  market                       180519 non-null  str
 25  order_city                   180519 non-null  str
 26  order_country                180519 non-null  str
 27  order_customer_id            180519 non-null  int64
 28  order_date_dateorders        180519 non-null  datetime64[us]
 29  order_id                     180519 non-null  int64
 30  order_item_cardprod_id       180519 non-null  int64
 31  order_item_discount          180519 non-null  float64
 32  order_item_discount_rate     180519 non-null  float64
 33  order_item_id                180519 non-null  int64
 34  order_item_product_price     180519 non-null  float64
 35  order_item_profit_ratio      180519 non-null  float64
 36  order_item_quantity          180519 non-null  int64
 37  sales                        180519 non-null  float64
 38  order_item_total             180519 non-null  float64
 39  order_profit_per_order       180519 non-null  float64
 40  order_region                 180519 non-null  str
 41  order_state                  180519 non-null  str
 42  order_status                 180519 non-null  str
 43  product_card_id              180519 non-null  int64
 44  product_category_id          180519 non-null  int64
 45  product_image                180519 non-null  str
 46  product_name                 180519 non-null  str
 47  product_price                180519 non-null  float64
 48  product_status               180519 non-null  int64
 49  shipping_date_dateorders     180519 non-null  datetime64[us]
 50  shipping_mode                180519 non-null  str
 51  order_year                   180519 non-null  int32
 52  order_month                  180519 non-null  int32
 53  order_month_name             180519 non-null  str
 54  order_day                    180519 non-null  int32
 55  order_weekday                180519 non-null  str
dtypes: datetime64[us](2), float64(13), int32(3), int64(14), str(24)
memory usage: 127.6 MB

In [18]:
# Calculate Delivery Time
df["delivery_time"] = (
    df["shipping_date_dateorders"] - df["order_date_dateorders"]
).dt.days

In [19]:
df[["days_for_shipping_real", "delivery_time"]].head()

   days_for_shipping_real  delivery_time
0                       3              3
1                       5              5
2                       4              4
3                       3              3
4                       2              2

In [20]:
df["profit_margin"] = (
    df["order_profit_per_order"] / df["sales"]
) * 100

In [21]:
df["discount_percentage"] = (
    df["order_item_discount"] / df["sales"]
) * 100

In [31]:
## Export Cleaned Dataset
df.to_csv("DataCoSupplyChain_Cleaned.csv", index=False)

In [22]:
df.describe()

,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,late_delivery_risk,category_id,customer_id,customer_zipcode,department_id,latitude,...,product_category_id,product_price,product_status,shipping_date_dateorders,order_year,order_month,order_day,delivery_time,profit_margin,discount_percentage
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.0,180519,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,31.851451,141.232550,0.0,2016-06-16 05:45:23.202433,2015.971150,6.235449,15.739346,3.471856,10.832612,10.139749
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,2.000000,9.990000,0.0,2015-01-03 00:00:00,2015.000000,1.000000,1.000000,0.000000,-274.999998,0.000000
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,18.000000,50.000000,0.0,2015-09-25 06:59:00,2015.000000,3.000000,8.000000,2.000000,6.224000,4.000307
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,29.000000,59.990002,0.0,2016-06-15 08:32:00,2016.000000,6.000000,16.000000,3.000000,24.251212,9.965338
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,45.000000,199.990005,0.0,2017-03-04 21:29:00,2017.000000,9.000000,23.000000,5.000000,33.601431,16.000800
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,76.000000,1999.989990,0.0,2018-02-06 22:14:00,2018.000000,12.000000,31.000000,6.000000,50.044288,25.043329
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,15.640064,139.732492,0.0,NaN,0.829429,3.403571,8.821895,1.670471,42.059372,7.059167